create table greetings (
  id bigint generated by default as identity primary key,
  text text
  email text
  video text
);

alter table greetings enable row level security;

create policy "Users can add greetings" on greetings for
    insert with check (true);

create policy "Everyone can view greetings" on greetings for
    select using (true);
